### PR TITLE
Add more options for streaming

### PR DESCRIPTION
**Pull request by wyegelwel**
This provides additional datatypes that are streamed back for server responses.

### CODE REVIEW

**Comment by wyegelwel** [comment]
I ran the tests before my changes and they had the same failures.

**Comment by mpenet** [comment]
LGTM, thanks

**Comment by mpenet** [comment]
It's on clojars as 0.6.5 FYI.

**Comment by mpenet** [comment]
Also, I updated the dependencies for this version and jetty-9.3.0 now requires java8, let me know if that's an issue, I might do a parallel release with the previous jetty version if needed.

**Comment by wyegelwel** [comment]
Thank you! If it isn't terribly inconvenient, can you also push the previous version?

**Comment by mpenet** [comment]
There's an easier way actually, you can just add a lein exclusion for the jetty-9.3.x and put back 9.2.x instead in your dependencies.
This commit should help you finding the the versions

**Comment by wyegelwel** [comment]
Thanks! I will give that a shot

**Pull request merged**
